### ISSUE TITLE
Please remove from Odoo appstore

### ISSUE THREAD

**Issue by JordiBForgeFlow** [sohaibrafiq/my_addons#1]
Hello @sohaibrafiq I am the author of the module "project_wbs".

You have modified this module, apparently to make it work for v8, and then published it in the odoo app store, but I'm receiving complains that the module fails.

You can use this module in v8 here:
https://github.com/projectexpert/pmis/tree/8.0/project_wbs

Can you please remove the module from the appstore?

Thanks,
Jordi.

**Comment by sohaibrafiq** [comment]
You please remove it yourself

**Comment by JordiBForgeFlow** [comment]
Ok, done!

**Comment by muralikrishnareddy** [comment]
How you did that, please explain me the procedure, whether we have to delete from Github or apps.odoo.com?
